### ISSUE TITLE
Update Website Articles (Production)

### ISSUE THREAD

**Issue by ez500** [frc461/website-2024#28]
No commits required for this one... just an indicator of an issue to make sure that the production database and website are up to date with all the up to date pages.

**Comment by ez500** [comment]
Don't close an issue/todo until it's resolved-- again, this does not need any commits or its own branch, but this is just to indicate that the articles on the production website are up to date.

**Comment by Gerseneck** [comment]
There's like no point in having a pr on something that isn't our job. It's not like media/outreach would look at the GitHub issues or anything.

**Comment by ez500** [comment]
I'm implying we don't need a PR, this is just an issue and an indicator that the production website is up and needs to be initially up-to-date.

**Comment by ez500** [comment]
Once the production website is up-to-date this issue should be resolved

**Comment by Gerseneck** [comment]
Yeah, but like instead of making a GitHub issue, you should mention it in tomorrow's meeting.

**Comment by ez500** [comment]
I will make sure OI/Media tend to this issue. It's just relevant to the website particularly the production database.
